version: '3'
services:
  # DON'T FORGET TO CHANGE THE XX WITH YOUR PORT
  # YOUR_USER WITH YOUR UNIX USER
  postgres_db:
    image: postgres:14-alpine
    container_name: "postgres33"
    environment:
      POSTGRES_PASSWORD: "Renata.2198"
      POSTGRES_DB: "renata_hurtadodb"
      POSTGRES_USER: "renata_hurtado"
    ports:
      - "10033:5533"
    volumes:
      - "/home/renata_hurtado/postgres:/usr/src/postgres"
    networks:
      - our-library-net
    command: -p 5533

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8033"
    container_name: "django33"
    depends_on: 
      - postgres_db
    environment:
      PSQL_DBNAME: "renata_hurtadodb"
      PSQL_USERNAME: "renata_hurtado"
      PSQL_PASS: "Renata.2198"
      PSQL_HOST: "postgres_db"
      PSQL_PORT: "5533"
    volumes:
      # "RUTA/DEL/SERVIDOR:RUTA/DENTRO/DEL/CONTENEDOR"
      - "/home/renata_hurtado/github-classroom/enroute-rockstars8g/django-assignment-renatahdo:/usr/src/django/library"
    ports:
      - "9033:8033"
    networks:
      - our-library-net
      
networks:
  our-library-net:
    external: true
    driver: bridge