# Generated by Django 4.0.3 on 2022-04-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='books_authors',
        ),
        migrations.RemoveField(
            model_name='booksauthors',
            name='author',
        ),
        migrations.RemoveField(
            model_name='booksauthors',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BooksAuthors',
        ),
    ]
